openapi: 3.0.3
info:
  title: Tezos Indexer Rarible API
  version: "0.1"
paths:
  /v0.1/items/all:
    description: Returns all NFT items
    get:
      tags:
        - nft-item-controller
      description: Returns all NFT items
      operationId: getNftAllItems
      parameters:
        - name: lastUpdateFrom
          in: query
          required: false
          schema:
            type: string
        - name: lastUpdateTo
          in: query
          required: false
          schema:
            type: string
        - name: showDeleted
          in: query
          required: false
          schema:
            type: boolean
        - name: includeMeta
          in: query
          required: false
          schema:
            type: boolean
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 9007199254740992
        - name: continuation
          in: query
          required: false
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftItems'
      security: [ ]
  /v0.1/items/{itemId}:
    description: Get NFT item by id
    get:
      tags:
        - nft-item-controller
      description: Get NFT item by id
      operationId: getNftItemById
      parameters:
        - name: includeMeta
          in: query
          required: false
          schema:
            type: boolean
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFound'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftItem'
      security: [ ]
  /v0.1/items/{itemId}/meta:
    description: Get NFT item by meta id
    get:
      tags:
        - nft-item-controller
      description: Get NFT item by meta id
      operationId: getNftItemMetaById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftItemMeta'
      security: [ ]

  /v0.1/ownerships/all:
    description: Get NFT all ownerships
    get:
      tags:
        - nft-ownership-controller
      description: Get NFT all ownerships
      operationId: getNftAllOwnerships
      parameters:
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 9007199254740992
        - name: continuation
          in: query
          required: false
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftOwnerships'
      security: [ ]
  /v0.1/ownerships/{ownershipId}:
    description: Get NFT ownerships by id
    get:
      tags:
        - nft-ownership-controller
      description: Get NFT ownerships by id
      operationId: getNftOwnershipById
      parameters:
        - name: ownershipId
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFound'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftOwnership'
      security: [ ]

  /v0.1/collections/all:
    description: collections_all
    get:
      tags:
        - nft-collection-controller
      description: collections_all
      operationId: searchNftAllCollections
      parameters:
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 9007199254740992
        - name: continuation
          in: query
          required: false
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftCollections'
      security: [ ]
  /v0.1/collections/{collection}:
    description: collections_by_id
    get:
      tags:
        - nft-collection-controller
      description: collections_by_id
      operationId: getNftCollectionById
      parameters:
        - name: collection
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFound'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftCollection'
      security: [ ]

  /v0.1/orders/all:
    description: Get all orders
    get:
      tags:
        - order-controller
      description: Get all orders
      operationId: getOrdersAll
      parameters:
        - name: origin
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Address'
        - name: sort
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/ActivitySort'
        - name: status
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OrderStatus'
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 9007199254740992
        - name: continuation
          in: query
          required: false
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderPagination'
      security: [ ]
  /v0.1/orders/{id}:
    get:
      tags:
        - order-controller
      description: Get order by id
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFound'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      security: [ ]
  /v0.1/orders/byIds:
    description: Get order by ids
    post:
      tags:
        - order-controller
      description: Get order by ids
      operationId: getOrderByIds
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderIds'
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
      security: [ ]
