openapi: 3.0.3
info:
  title: Tezos Indexer Rarible API
  version: "0.1"
paths:
  /v0.1/orders/all:
    description: Get all orders
    get:
      tags:
        - order-controller
      description: Get all orders
      operationId: getOrdersAll
      parameters:
        - name: origin
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Address'
        - name: sort
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/ActivitySort'
        - name: status
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OrderStatus'
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 9007199254740992
        - name: continuation
          in: query
          required: false
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderPagination'
      security: [ ]
  /v0.1/orders/{id}:
    get:
      tags:
        - order-controller
      description: Get order by id
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFound'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      security: [ ]
  /v0.1/orders/byIds:
    description: Get order by ids
    post:
      tags:
        - order-controller
      description: Get order by ids
      operationId: getOrderByIds
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderIds'
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
      security: [ ]
